### ISSUE TITLE
你好，可以说一下缩略图预览、上下页功能怎么实现吗？

### ISSUE THREAD

**Issue by Amney521** [Lushenggang/pdf-preview#1]

**Comment by wintc23** [comment]
缩略图预览没明白是什么样的展现形式。
上下页功能的话，你看一下代码应该不难改写出来的，代码就是每页每页渲染的。

**Comment by hucongtb** [comment]
老哥永远展示第一次渲染的文件怎么解决 急

**Comment by wintc23** [comment]
> 老哥永远展示第一次渲染的文件怎么解决 急

啥意思，只显示前几页？

**Comment by hucongtb** [comment]
我有很多个pdf的文件，点击赋值 插件展示 但是第二次赋值了可是展示的永远是第一次渲染的文件

**Comment by wintc23** [comment]
> 我有很多个pdf的文件，点击赋值 插件展示 但是第二次赋值了可是展示的永远是第一次渲染的文件

重新调用加载文件函数了吗？你看下有个根据文件地址获取p地方文件的函数，如果你的文件路径修改了，应该调用一次这个函数并且对其它变量重新初始化

**Comment by hucongtb** [comment]
我看代码中watch有监听url，会自己调这个函数 我在监听器中先把其他变量清空就可以啦 感谢老哥

**Comment by wintc23** [comment]
> 我看代码中watch有监听url，会自己调这个函数 我在监听器中先把其他变量清空就可以啦 感谢老哥

咦，改变url这个我确实测试不充分，应该是要清空变量的。可以提个pr合并一下~
